### Criar um novo evento
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Romario e Juliana",
  "details": "casamento",
  "maximumAttendees": 150
}

###
### Criar o participante no evento
POST http://localhost:3333/events/7e0d5d80-33ab-430a-8e2e-292a68d543dd/attendees
Content-Type: application/json

{
  "name": "Matheus Bourguignon",
  "email": "matheusmbl21@gmail.com"
}

### Create Account
POST http://localhost:3333/create-account
Content-Type: application/json

{
  "name": "Matheus Bourguignon",
  "email": "matheusmbl21@gmail.com",
  "password": "123456",
  "cellphone": "21982482673",
  "birthdate": "1998-04-16"
}


### Buscar Conta Completa (GET)
GET http://localhost:3333/account/46b68fa0-da5f-4c1c-80c4-2c4ca8cedb58
Content-Type: application/json


### Teste de Login
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "matheusmbl21@gmail.com",
  "password": "aaaaaa"
}


### Atualizar os dados de um usuário existente
PUT http://localhost:3333/update-account
Content-Type: application/json

{
  "userId": "7534270e-69a0-45b1-b33b-b4b67d17e65c",
  "name": "Johnathan Doe", 
  "email": "johnathandoe@example.com", 
  "birthdate": "1990-02-02",
  "cellphone": "0987654321",
  "password": "newstrongpassword"
}



###
### Descrição do evento
GET http://localhost:3333/events/6b440ae6-860e-4774-852f-011eb70f2399

###

### Procurar o participante no evento
GET http://localhost:3333/attendees/1/badge


###

### Verifica a entrada do usuário 
GET http://localhost:3333/attendees/1/check-in


###

### Esse método está buscando todos os participantes do evento
GET http://localhost:3333/events/6b440ae6-860e-4774-852f-011eb70f2399/attendees?query=matheus