### Criar um novo evento
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1,
}

###
### Criar o participante no evento
POST http://localhost:3333/events/6b440ae6-860e-4774-852f-011eb70f2399/attendees
Content-Type: application/json

{
  "name": "Matheus Bourguignon",
  "email": "matheusmbl21@gmail.com"
}

### Criar conta com sucesso
POST http://localhost:3333/create-account
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.silva@example.com",
  "password": "senha123",
  "date_of_birth": "1998-04-16",
  "cellphone": 11987654321
}


###
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "email": "joao.silva@example.com",
  "password": "senha123",
}


###
### Descrição do evento
GET http://localhost:3333/events/6b440ae6-860e-4774-852f-011eb70f2399

###

### Procurar o participante no evento
GET http://localhost:3333/attendees/1/badge


###

### Verifica a entrada do usuário 
GET http://localhost:3333/attendees/2/check-in


###

### Esse método está buscando todos os participantes do evento
GET http://localhost:3333/events/6b440ae6-860e-4774-852f-011eb70f2399/attendees?query=matheus